# Generated by Django 2.1.5 on 2020-11-18 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=2000)),
                ('director', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('imdbRating', models.CharField(max_length=200)),
                ('metascore', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
