# Generated by Django 2.1.5 on 2020-12-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=2000)),
                ('director', models.CharField(max_length=200)),
                ('imdbRating', models.CharField(max_length=200)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topmovie', to='MovieTools.Genre')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
