# Generated by Django 2.1.5 on 2020-12-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='metascore',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
