# Generated by Django 2.1.5 on 2020-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
