# Generated by Django 2.1.5 on 2020-11-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0002_todolist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='detail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
